=== kim-ji-woong/une_solution_old/web/SOP/WebContent/XML/SOP.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- Version 1.3-->
  <!-- - Process Property일 경우 MissionList 추가 -->
  <!-- Version 1.1-->
  <!-- - TRANSMISSION 추가 -->
  <xs:element name="SOP">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="1">
        <xs:element name="Header">
          <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="1">
              <xs:element name="XMLVersion" type="xs:string"/>
              <xs:element name="Category" type="xs:string" />
              <xs:element name="SubCategory" type="xs:string" />
              <xs:element name="Disaster" type="xs:string" />
              <xs:element name="Regular" type="xs:boolean" />
              <xs:element name="Normal" type="xs:boolean" />
              <xs:element name="SOPVersion">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="description" type="xs:string" use="optional" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Body">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ActionStepList" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ActionStep" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="StepName" type="xs:string" minOccurs="1" maxOccurs="1"/>
                          <xs:element name="PeriodType" type="typePeriodType" minOccurs="1" maxOccurs="1"/>
                          <xs:element name="BeginTime" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
                          <xs:element name="EndTime" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
                          <xs:element name="WeekDayOption" type="typeWeekDayOption" minOccurs="1" maxOccurs="1"/>
                          <xs:element name="Iteration" type="xs:unsignedInt" minOccurs="1" maxOccurs="1"/>
                          <xs:element name="IterationType" type="typeIterationType" minOccurs="1" maxOccurs="1"/>
                          <xs:element name="ProcessTime" type="xs:unsignedInt" minOccurs="1" maxOccurs="1"/>
                          <xs:element name="ProcessTimeType" type="typeProcessTimeType" minOccurs="0" maxOccurs="1"/>
                          <xs:element name="ParentStepID" type="xs:int" minOccurs="0" maxOccurs="1"/>
                          <xs:element name="StepMemberList" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="StepMember" minOccurs="1" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="ComponentList" minOccurs="1" maxOccurs="1">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="Component" minOccurs="0" maxOccurs="unbounded">
                                              <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="X" type="xs:float" minOccurs="1" maxOccurs="1"/>
                                                  <xs:element name="Y" type="xs:float" minOccurs="1" maxOccurs="1"/>
                                                  <xs:element name="Width" type="xs:float" minOccurs="1" maxOccurs="1"/>
                                                  <xs:element name="Height" type="xs:float" minOccurs="1" maxOccurs="1"/>
                                                  <xs:element name="Text" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                                  <xs:element name="ComponentID" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                                  <xs:element name="Property" >
                                                    <xs:complexType>
                                                      <xs:sequence>
													    <xs:element minOccurs="0" maxOccurs="1" name="GroupItems" type="xs:string" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="useSMS" type="xs:boolean" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="SMSText" type="xs:string" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="SMSExternalTeamIDList" type="xs:string" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="useFax" type="xs:boolean" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="FaxExternalTeamIDList" type="xs:string" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="usePopupMessage" type="xs:boolean" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="useMobileApp" type="xs:boolean" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="useBroadcast" type="xs:boolean" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="broadcastMessage" type="xs:string" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="LinkedActionStep">
                                                          <xs:complexType>
                                                            <xs:sequence>
                                                              <xs:element name="CategoryName" minOccurs="1" maxOccurs="1" type="xs:string"/>
                                                              <xs:element name="SubCategoryName" minOccurs="1" maxOccurs="1" type="xs:string"/>
                                                              <xs:element name="DisasterName" minOccurs="1" maxOccurs="1" type="xs:string"/>
                                                              <xs:element name="ActionStepName" minOccurs="1" maxOccurs="1" type="xs:string"/>
                                                              <xs:element name="ParentActionStepName" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                                                            </xs:sequence>
                                                          </xs:complexType>
                                                        </xs:element>
                                                        <xs:element minOccurs="0" maxOccurs="1" name="LinkedComponentName" type="xs:string" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="LinkedStepMemberIndex" type="xs:unsignedInt" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="LinkedComponentID" type="xs:int" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="isBegin" type="xs:boolean" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="TeamList" type="xs:string" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="ProcessTime" type="xs:unsignedInt" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="ProcessTimeType" type="typeProcessTimeType" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="useProcessTime" type="xs:boolean" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="useMissionMessage" type="xs:boolean" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="onlyTeamLeader" type="xs:boolean" />
                                                        <xs:element minOccurs="0" maxOccurs="1" name="MissionList">
                                                          <xs:complexType>
                                                            <xs:sequence>
                                                              <xs:element name="Mission" minOccurs="0" maxOccurs="unbounded">
                                                                <xs:complexType>
                                                                  <xs:simpleContent>
                                                                    <xs:extension base="xs:string">
                                                                      <xs:attribute name="transmissionType" type="xs:int" use="required" />
                                                                      <xs:attribute name="target" type="xs:string" use="required" />
                                                                    </xs:extension>
                                                                  </xs:simpleContent>
                                                                </xs:complexType>
                                                              </xs:element>
                                                            </xs:sequence>
                                                          </xs:complexType>
                                                        </xs:element>
                                                        <xs:element minOccurs="0" maxOccurs="1" name="Internal">
                                                          <xs:complexType>
                                                            <xs:sequence minOccurs="1" maxOccurs="1">
                                                              <xs:element name="usePopupMessage" type="xs:boolean" />
                                                              <xs:element name="useMobileApp" type="xs:boolean" />
                                                              <xs:element name="useBroadcast" type="xs:boolean" />
                                                              <xs:element name="broadcastMessage" type="xs:string" />
                                                            </xs:sequence>
                                                          </xs:complexType>
                                                        </xs:element>
                                                        <xs:element minOccurs="0" maxOccurs="1" name="External">
                                                          <xs:complexType>
                                                            <xs:sequence>
                                                              <xs:element minOccurs="1" maxOccurs="1" name="useSMS" type="xs:boolean" />
                                                              <xs:element minOccurs="0" maxOccurs="1" name="SMSText" type="xs:string" />
                                                              <xs:element minOccurs="0" maxOccurs="1" name="SMSExternalTeamIDList" type="xs:string" />
                                                              <xs:element minOccurs="1" maxOccurs="1" name="useFax" type="xs:boolean" />
                                                              <xs:element minOccurs="0" maxOccurs="1" name="FaxExternalTeamIDList" type="xs:string" />
                                                            </xs:sequence>
                                                          </xs:complexType>
                                                        </xs:element>
                                                      </xs:sequence>
                                                      <xs:attribute name="type" type="typeComponentType" use="required" />
                                                    </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:int" use="required" />
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="ArrowList" minOccurs="1" maxOccurs="1">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="Arrow" minOccurs="0" maxOccurs="unbounded">
                                              <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Text" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                                  <xs:element name="BeginComponentID" type="xs:int" minOccurs="1" maxOccurs="1"/>
                                                  <xs:element name="BeginComponentPosition" type="typeArrowPosition" minOccurs="1" maxOccurs="1"/>
                                                  <xs:element name="EndComponentID" type="xs:int" minOccurs="1" maxOccurs="1"/>
                                                  <xs:element name="EndComponentPosition" type="typeArrowPosition" minOccurs="1" maxOccurs="1"/>
                                                </xs:sequence>
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:int" use="required" />
                                    <xs:attribute name="type" type="typeTeamType" use="required" />
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="typePeriodType">
    <xs:restriction base="xs:int">
      <!-- 0 : (사용 안함) -->
      <xs:enumeration value="0" />
      <!-- 1 : (날짜 옵션, n1월 n2일 ~ m1월 m2일까지) -->
      <xs:enumeration value="1" />
      <!-- 2 : (시간 옵션, n1시 n2분 ~ m1월 m2일까지) -->
      <xs:enumeration value="2" />
      <!-- 3 : (날짜 옵션 + 시간 옵션) -->
      <xs:enumeration value="3" />
      <!-- 11 : (날짜 옵션, n1월 n2일 ~ m1월 m2일까지) + 고정년도 사용-->
      <xs:enumeration value="11" />
      <!-- 12 : (시간 옵션, n1시 n2분 ~ m1월 m2일까지) + 고정년도 사용 -->
      <xs:enumeration value="12" />
      <!-- 13 : (날짜 옵션 + 시간 옵션) + 고정년도 사용 -->
      <xs:enumeration value="13" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typeWeekDayOption">
    <!-- 요일 옵션(bit 연산), bit : 1(일요일), 2(월요일), 4(화요일), 8(수요일), 16(목요일), 32(금요일), 64(토요일) -->
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="127" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typeIterationType">
    <!-- 반복 회수 옵션 : 0(전체 기간중 몇회), 1(년중 몇회), 2(월중 몇회), 3(주중 몇회), 4(하루중 몇회), 5(시간당 몇회) -->
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="5" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typeProcessTimeType">
    <!-- 처리시간 옵션 : 0(개월), 1(주), 2(일), 3(시간), 4(분), 5(알 수 없음) -->
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="5" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typeComponentType">
    <!-- ComponentType { PROCESS = 0, DECISION, ANNOTATION, ENDPOINT, LINK, TRANSSOP, INTERNAL, EXTERNAL, TRANSMISSION, GROUP } -->
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="9" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typeArrowPosition">
    <!-- Component의 어느쪽에 화살표가 붙어 있는가?(0 : Top, 1 : Right, 2 : Bottom, 3 : Left) -->
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="3" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typeTeamType">
    <!-- 0(평일 비상 조직), 1(휴일 비상 조직), 2(외부 기관), 3(사용자 정의 조직), 4(정규 조직) -->
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="3" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== kim-ji-woong/une_solution_old/src/PreSafe/SenarioService/App_Data/강간형_기본형1.xml
<?xml version="1.0" encoding="utf-8"?>
<SOP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://unes.iptime.org:9808/SOP/XML/SOP.xsd">
  <Header>
    <XMLVersion>V1.4</XMLVersion>
    <Category>UnE</Category>
    <SubCategory>SOP</SubCategory>
    <Disaster>강간형</Disaster>
    <Regular>0</Regular>
    <Normal>1</Normal>
    <SOPVersion>공통_기본형1</SOPVersion>
  </Header>
  <Body>
    <ActionStepList>
      <ActionStep id="1" selected="1">
        <StepName>새시나리오</StepName>
        <PeriodType>0</PeriodType>
        <WeekDayOption>127</WeekDayOption>
        <Iteration>0</Iteration>
        <IterationType>0</IterationType>
        <ProcessTime>0</ProcessTime>
        <StepMemberList>
          <StepMember id="1" type="0" name="Main">
            <ComponentList>
              <Component id="1">
                <X>179.8065</X>
                <Y>76.38</Y>
                <Width>100</Width>
                <Height>40</Height>
                <Text>START</Text>
                <ComponentID>새시나리오_Main_EndPoint_1</ComponentID>
                <Property type="3">
                  <isBegin>1</isBegin>
                </Property>
              </Component>
              <Component id="2">
                <X>1024.511</X>
                <Y>2201.515</Y>
                <Width>100</Width>
                <Height>40</Height>
                <Text>END</Text>
                <ComponentID>새시나리오_Main_EndPoint_2</ComponentID>
                <Property type="3">
                  <isBegin>0</isBegin>
                </Property>
              </Component>
              <Component id="3">
                <X>129.8065</X>
                <Y>312.3998</Y>
                <Width>200</Width>
                <Height>85</Height>
                <Text>정태형 인가?</Text>
                <ComponentID>새시나리오_Main_Decision_1</ComponentID>
                <Property type="1">
                  <UserData name="expr" value="(CL)==0">(CL)==0</UserData>
                </Property>
              </Component>
              <Component id="4">
                <X>129.8065</X>
                <Y>175.3067</Y>
                <Width>200</Width>
                <Height>82</Height>
                <Text>범죄 가능성 = 0</Text>
                <ComponentID>새시나리오_Main_Process_2</ComponentID>
                <Property type="0">
                  <TeamList>
                  </TeamList>
                  <ProcessTime>0</ProcessTime>
                  <ProcessTimeType>5</ProcessTimeType>
                  <useProcessTime>0</useProcessTime>
                  <useMissionMessage>0</useMissionMessage>
                  <MissionList>
                  </MissionList>
                  <UserData name="expr" value="(CR)=0">(CR)=0</UserData>
                  <UserData name="showExpr" value="False">False</UserData>
                </Property>
              </Component>
              <Component id="5">
                <X>129.8065</X>
                <Y>472.1197</Y>
                <Width>200</Width>
                <Height>82</Height>
                <Text>정태형 범죄 가능성 산정</Text>
                <ComponentID>새시나리오_Main_Process_3</ComponentID>
                <Property type="0">
                  <TeamList>
                  </TeamList>
                  <ProcessTime>0</ProcessTime>
                  <ProcessTimeType>5</ProcessTimeType>
                  <useProcessTime>0</useProcessTime>
                  <useMissionMessage>0</useMissionMessage>
                  <MissionList>
                  </MissionList>
                  <UserData name="expr" value="(CR)=(CR)+(15*3)">(CR)=(CR)+(15*3)</UserData>
                  <UserData name="showExpr" value="False">False</UserData>
                </Property>
              </Component>
              <Component id="6">
                <X>891.5511</X>
                <Y>312.3998</Y>
                <Width>200</Width>
                <Height>85</Height>
                <Text>접근금지구역인가?</Text>
                <ComponentID>새시나리오_Main_Decision_2</ComponentID>
                <Property type="1">
                  <UserData name="expr" value="(CL)==3">(CL)==3</UserData>
                </Property>
              </Component>
              <Component id="7">
                <X>891.5511</X>
                <Y>470.4417</Y>
                <Width>200</Width>
                <Height>82</Height>
                <Text>접근금지구역 범죄 가능성 산정</Text>
                <ComponentID>새시나리오_Main_Process_4</ComponentID>
                <Property type="0">
                  <TeamList>
                  </TeamList>
                  <ProcessTime>0</ProcessTime>
                  <ProcessTimeType>5</ProcessTimeType>
                  <useProcessTime>0</useProcessTime>
                  <useMissionMessage>0</useMissionMessage>
                  <MissionList>
                  </MissionList>
                  <UserData name="expr" value="(CR)=(CR)+(60*2.5)">(CR)=(CR)+(60*2.5)</UserData>
                  <UserData name="showExpr" value="False">False</UserData>
                </Property>
              </Component>
              <Component id="8">
                <X>1377.899</X>
                <Y>461.0199</Y>
                <Width>200</Width>
                <Height>82</Height>
                <Text>기타 구역 범죄 가능성 산정</Text>
                <ComponentID>새시나리오_Main_Process_5</ComponentID>
                <Property type="0">
                  <TeamList>
                  </TeamList>
                  <ProcessTime>0</ProcessTime>
                  <ProcessTimeType>5</ProcessTimeType>
                  <useProcessTime>0</useProcessTime>
                  <useMissionMessage>0</useMissionMessage>
                  <MissionList>
                  </MissionList>
                  <UserData name="expr" value="(CR)=(CR)+(85*3)&#xD;&#xA;">(CR)=(CR)+(85*3)
</UserData>
                  <UserData name="showExpr" value="False">False</UserData>
                </Property>
              </Component>
              <Component id="9">
                <X>129.8065</X>
                <Y>603.4637</Y>
                <Width>200</Width>
                <Height>85</Height>
                <Text>고위험대시간인가?</Text>
                <ComponentID>새시나리오_Main_Decision_3</ComponentID>
                <Property type="1">
                  <UserData name="expr" value="((CHOUR)&gt;=12 &amp;&amp; (CHOUR) &lt; 18) || ((CHOUR) &gt;=20 &amp;&amp; (CHOUR) &lt;24) || ((CHOUR)&gt;=0 &amp;&amp; (CHOUR) &lt; 4)">((CHOUR)&gt;=12 &amp;&amp; (CHOUR) &lt; 18) || ((CHOUR) &gt;=20 &amp;&amp; (CHOUR) &lt;24) || ((CHOUR)&gt;=0 &amp;&amp; (CHOUR) &lt; 4)</UserData>
                </Property>
              </Component>
              <Component id="10">
                <X>369.0274</X>
                <Y>681.4637</Y>
                <Width>200</Width>
                <Height>85</Height>
                <Text>중위험대 시간인가?</Text>
                <ComponentID>새시나리오_Main_Decision_4</ComponentID>
                <Property type="1">
                  <UserData name="expr" value="((CHOUR)&gt;=9 &amp;&amp; (CHOUR) &lt; 12) || ((CHOUR) &gt;=18 &amp;&amp; (CHOUR) &lt;20)">((CHOUR)&gt;=9 &amp;&amp; (CHOUR) &lt; 12) || ((CHOUR) &gt;=18 &amp;&amp; (CHOUR) &lt;20)</UserData>
                </Property>
              </Component>
              <Component id="11">
                <X>129.8065</X>
                <Y>827.4637</Y>
                <Width>200</Width>
                <Height>82</Height>
                <Text>고위험대 시간 범죄 가능성 산정</Text>
                <ComponentID>새시나리오_Main_Process_6</ComponentID>
                <Property type="0">
                  <TeamList>
                  </TeamList>
                  <ProcessTime>0</ProcessTime>
                  <ProcessTimeType>5</ProcessTimeType>
                  <useProcessTime>0</useProcessTime>
                  <useMissionMessage>0</useMissionMessage>
                  <MissionList>
                  </MissionList>
                  <UserData name="expr" value="(CR)=(CR)+(70*3)">(CR)=(CR)+(70*3)</UserData>
                  <UserData name="showExpr" value="False">False</UserData>
                </Property>
              </Component>
              <Component id="12">
                <X>369.0274</X>
                <Y>825</Y>
                <Width>200</Width>
                <Height>82</Height>
                <Text>중위험대 시간 범죄 가능성 산정</Text>
                <ComponentID>새시나리오_Main_Process_7</ComponentID>
                <Property type="0">
                  <TeamList>
                  </TeamList>
                  <ProcessTime>0</ProcessTime>
                  <ProcessTimeType>5</ProcessTimeType>
                  <useProcessTime>0</useProcessTime>
                  <useMissionMessage>0</useMissionMessage>
                  <MissionList>
                  </MissionList>
                  <UserData name="expr" value="(CR)=(CR)+(25*3)">(CR)=(CR)+(25*3)</UserData>
                  <UserData name="showExpr" value="False">False</UserData>
                </Property>
              </Component>
              <Component id="13">
                <X>603</X>
                <Y>825.5164</Y>
                <Width>200</Width>
                <Height>82</Height>
                <Text>저위험대 시간 범죄 가능성 산정</Text>
                <ComponentID>새시나리오_Main_Process_8</ComponentID>
                <Property type="0">
                  <TeamList>
                  </TeamList>
                  <ProcessTime>0</ProcessTime>
                  <ProcessTimeType>5</ProcessTimeType>
                  <useProcessTime>0</useProcessTime>
                  <useMissionMessage>0</useMissionMessage>
                  <MissionList>
                  </MissionList>
                  <UserData name="expr" value="(CR)=(CR)+(5*3)">(CR)=(CR)+(5*3)</UserData>
                  <UserData name="showExpr" value="False">False</UserData>
                </Property>
              </Component>
              <Component id="14">
                <X>129.8065</X>
                <Y>992.7852</Y>
