=== kim-ji-woong/une_solution_old/doc/SensorMaker/UnE.Space.Sensor.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="UnE.Space.Sensor">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Spaces" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Site" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="BuildingGroups" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="BuildingGroup">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
													<xs:element name="ParentBuildingGroupID" type="xs:string" minOccurs="0" maxOccurs="1"/>
													<xs:element name="TextCenter" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element ref="Point3D" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="DisplayText" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="id" type="xs:ID" use="required" />
												<xs:attribute name="parentBuildingGroupID" type="xs:string" use="optional" />
											</xs:complexType>
											<xs:keyref name="ParentBuildingGroupIDRef" refer="BuildingGroupID">
												<xs:selector xpath="." />
												<xs:field xpath="ParentBuildingGroupID" />
											</xs:keyref>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Buildings" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="Building">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Code" minOccurs="0" maxOccurs="1"/>
													<xs:element name="Name" minOccurs="1" maxOccurs="1"/>
													<xs:element name="BuildingGroupID" type="xs:string" minOccurs="1" maxOccurs="1"/>
													<xs:element name="MaxFloor" minOccurs="1" maxOccurs="1"/>
													<xs:element name="MinFloor" minOccurs="1" maxOccurs="1"/>
													<xs:element name="TextCenter" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="1" maxOccurs="1">
																<xs:element name="Point3D" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="DisplayText" minOccurs="0" maxOccurs="1"/>
													<xs:element name="BroadcastText" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="id" type="xs:ID" use="required" />
											</xs:complexType>
											<xs:keyref name="BuildingGroupIDRef" refer="BuildingGroupID">
												<xs:selector xpath="." />
												<xs:field xpath="BuildingGroupID" />
											</xs:keyref>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Zones" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="Zone">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" minOccurs="1" maxOccurs="1"/>
													<!-- BuildingID가 없으면 외부영역 -->
													<xs:element name="BuildingID" type="xs:string" minOccurs="0" maxOccurs="1"/>
													<!-- FloorIndex가 없어도 외부영역 -->
													<xs:element name="FloorIndex" minOccurs="0" maxOccurs="1"/>
													<xs:element name="AddFloor" minOccurs="0" maxOccurs="1"/>
													<xs:element name="Boundary" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element ref="Polygon" minOccurs="1" maxOccurs="1" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="TextCenter" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="1" maxOccurs="1">
																<xs:element ref="Point3D" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="DisplayText" minOccurs="0" maxOccurs="1"/>
													<xs:element name="BroadcastText" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="id" type="xs:ID" use="required" />
											</xs:complexType>
											<xs:keyref name="BuildingIDRef" refer="BuildingID">
												<xs:selector xpath="." />
												<xs:field xpath="BuildingID" />
											</xs:keyref>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="EquipmentZones" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="EquipmentZone">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" minOccurs="1" maxOccurs="1"/>
													<xs:element name="Boundary" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element ref="Polygon" minOccurs="1" maxOccurs="1" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="LinkedZoneIDList" minOccurs="1" maxOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="1" maxOccurs="unbounded">
																<xs:element name="ZoneID" type="xs:string" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="Type" minOccurs="0" maxOccurs="1"/>
													<xs:element name="TextCenter" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="1" maxOccurs="1">
																<xs:element ref="Point3D" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="DisplayText" minOccurs="0" maxOccurs="1"/>
													<xs:element name="BroadcastText" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="id" type="xs:ID" use="required" />
											</xs:complexType>
											<xs:keyref name="ZoneIDRef" refer="ZoneID">
												<xs:selector xpath="./LinkedZoneIDList" />
												<xs:field xpath="ZoneID" />
											</xs:keyref>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Sensors" minOccurs="1" maxOccurs="1">					
					<xs:complexType>
						<xs:sequence>
							<xs:element name="SensorTypes" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="SensorType">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="id" type="xs:ID" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="FireSensorSubTypes" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="FireSensorSubType">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="id" type="xs:ID" use="required" />
											</xs:complexType>											
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Materials" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="Material">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
													<xs:element name="UOM" type="xs:string" minOccurs="1" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="id" type="xs:ID" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="FireSensors" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="Fire">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
													<xs:element name="PositionName" type="xs:string" minOccurs="0" maxOccurs="1"/>
													<xs:element name="Position" minOccurs="1" maxOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="0" maxOccurs="1">
																<xs:element ref="Point3D" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="ZoneID" type="xs:string" minOccurs="1" maxOccurs="1"/>
													<xs:element name="EquipZoneID" type="xs:string" minOccurs="0" maxOccurs="1"/>
													<xs:element name="SensorSubType" type="xs:string" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="id" type="xs:ID" use="required" />
											</xs:complexType>
											<xs:keyref name="FireZoneIDRef" refer="ZoneID">
												<xs:selector xpath="." />
												<xs:field xpath="ZoneID" />
											</xs:keyref>
											<xs:keyref name="FireEquipZoneIDRef" refer="EquipZoneID">
												<xs:selector xpath="." />
												<xs:field xpath="EquipZoneID" />
											</xs:keyref>
											<xs:keyref name="FireSensorSubTypeIDRef" refer="FireSensorSubTypeID">
												<xs:selector xpath="." />
												<xs:field xpath="SensorSubType" />
											</xs:keyref>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="PSMSensors" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="PSM">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
													<xs:element name="PositionName" type="xs:string" minOccurs="0" maxOccurs="1"/>
													<xs:element name="Position" minOccurs="1" maxOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="0" maxOccurs="1">
																<xs:element ref="Point3D" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="ZoneID" type="xs:string" minOccurs="1" maxOccurs="1"/>
													<xs:element name="EquipZoneID" type="xs:string" minOccurs="0" maxOccurs="1"/>
													<xs:element name="MaterialID" type="xs:string" minOccurs="1" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="id" type="xs:ID" use="required" />
											</xs:complexType>
											<xs:keyref name="PSMZoneIDRef" refer="ZoneID">
												<xs:selector xpath="." />
												<xs:field xpath="ZoneID" />
											</xs:keyref>
											<xs:keyref name="PSMEquipZoneIDRef" refer="EquipZoneID">
												<xs:selector xpath="." />
												<xs:field xpath="EquipZoneID" />
											</xs:keyref>
											<xs:keyref name="PSMMaterialIDRef" refer="MaterialID">
												<xs:selector xpath="." />
												<xs:field xpath="MaterialID" />
											</xs:keyref>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="EtcSensors" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="Etc">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
													<xs:element name="PositionName" type="xs:string" minOccurs="0" maxOccurs="1"/>
													<xs:element name="Position" minOccurs="1" maxOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="0" maxOccurs="1">
																<xs:element ref="Point3D" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="ZoneID" type="xs:string" minOccurs="1" maxOccurs="1"/>
													<xs:element name="EquipZoneID" type="xs:string" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="id" type="xs:ID" use="required" />
											</xs:complexType>
											<xs:keyref name="EtcZoneIDRef" refer="ZoneID">
												<xs:selector xpath="." />
												<xs:field xpath="ZoneID" />
											</xs:keyref>
											<xs:keyref name="EtcEquipZoneIDRef" refer="EquipZoneID">
												<xs:selector xpath="." />
												<xs:field xpath="EquipZoneID" />
											</xs:keyref>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="CCTVs" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="CCTV">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
													<xs:element name="PositionName" type="xs:string" minOccurs="0" maxOccurs="1"/>
													<xs:element name="Position" minOccurs="1" maxOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="0" maxOccurs="1">
																<xs:element ref="Point3D" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="ZoneID" type="xs:string" minOccurs="1" maxOccurs="1"/>
													<xs:element name="EquipZoneID" type="xs:string" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="id" type="xs:ID" use="required" />
											</xs:complexType>
											<xs:keyref name="CCTVZoneIDRef" refer="ZoneID">
												<xs:selector xpath="." />
												<xs:field xpath="ZoneID" />
											</xs:keyref>
											<xs:keyref name="CCTVEquipZoneIDRef" refer="EquipZoneID">
												<xs:selector xpath="." />
												<xs:field xpath="EquipZoneID" />
											</xs:keyref>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="required" />
		</xs:complexType>
		<xs:key name="BuildingGroupID">
			<xs:selector xpath="Spaces/BuildingGroups/BuildingGroup" />
			<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="BuildingID">
			<xs:selector xpath="Spaces/Buildings/Building" />
			<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="ZoneID">
			<xs:selector xpath="Spaces/Zones/Zone" />
			<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="EquipZoneID">
			<xs:selector xpath="Spaces/EquipmentZones/EquipmentZone" />
			<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="MaterialID">
			<xs:selector xpath="Sensors/Materials/Material" />
			<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="FireSensorSubTypeID">
			<xs:selector xpath="Sensors/FireSensorSubTypes/FireSensorSubType" />
			<xs:field xpath="@id" />
		</xs:key>
	</xs:element>
	<xs:element name="Point2D">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[+-]?[0-9][0-9]*[.]?[0-9]*,[+-]?[0-9][0-9]*[.]?[0-9]*" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Point3D">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[+-]?[0-9][0-9]*[.]?[0-9]*,[+-]?[0-9][0-9]*[.]?[0-9]*,[+-]?[0-9][0-9]*[.]?[0-9]*" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Polygon">
		<xs:complexType>
			<xs:sequence minOccurs="3" maxOccurs="unbounded">
				<xs:element ref="Point2D" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="BasicInfo" type="xs:string">
	</xs:element>		
</xs:schema>

=== kim-ji-woong/une_solution_old/doc/SensorMaker/UnE.Space.Sensor.xml
<?xml version="1.0" encoding="utf-8"?>
<UnE.Space.Sensor version="1.0" 
				 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="UnE.Space.Sensor.xsd">
	<Spaces>
		<Site>
			<Name>유엔이</Name>
		</Site>
		<BuildingGroups>
			<BuildingGroup id="BG_1">
				<Name>1동</Name>
				<!-- 생략가능 -->
				<!--ParentBuildingGroupID></ParentBuildingGroupID-->
				<!-- 생략가능 -->
				<TextCenter>
					<Point3D>0,0,0</Point3D>
				</TextCenter>
				<!-- 생략가능 -->
				<DisplayText>1동</DisplayText>
			</BuildingGroup>
			<BuildingGroup id="BG_2">
				<Name>2동</Name>
				<!-- 생략가능 -->
				<ParentBuildingGroupID>BG_1</ParentBuildingGroupID>
				<!-- 생략가능 -->
				<TextCenter>
					<Point3D>0,0,0</Point3D>
				</TextCenter>
				<!-- 생략가능 -->
				<DisplayText>2동</DisplayText>
			</BuildingGroup>
		</BuildingGroups>
		<Buildings>
			<Building id="B_1">
				<!-- 생략가능 -->
				<Code>1-1</Code>
				<Name>1-1공장</Name>
				<BuildingGroupID>BG_1</BuildingGroupID>
				<MaxFloor>0</MaxFloor>
				<MinFloor>0</MinFloor>
				<!-- 생략가능 -->
				<TextCenter>
					<Point3D>0,0,0</Point3D>
				</TextCenter>
				<!-- 생략가능 -->
				<DisplayText>1-1공장</DisplayText>
				<!-- 생략가능 -->
				<BroadcastText>일 다시 일 공장</BroadcastText>
			</Building>
		</Buildings>
		<Zones>
			<Zone id="Z_1">
				<Name>1-1공장 1층</Name>
				<!-- 생략시 외부영역 -->
				<BuildingID>B_1</BuildingID>
				<!-- 생략시 외부영역 -->
				<FloorIndex>0</FloorIndex>
				<!-- 생략가능 -->
				<Boundary>
					<!-- X, Y 좌표 List -->
					<Polygon>
						<Point2D>0,0</Point2D>
						<Point2D>10,0</Point2D>
						<Point2D>10,10</Point2D>
						<Point2D>0,10</Point2D>
					</Polygon>
				</Boundary>
				<!-- 생략가능 -->
				<TextCenter>
					<Point3D>0,0,0</Point3D>
				</TextCenter>
				<!-- 생략가능 -->
				<DisplayText>1-1공장 1층</DisplayText>
				<!-- 생략가능 -->
				<BroadcastText>일 다시 일 공장 일층</BroadcastText>
			</Zone>
		</Zones>
		<EquipmentZones>
			<EquipmentZone id="EZ_1">
				<Name>1-1공장 1층 사무실</Name>
				<!-- 생략가능 -->
				<Boundary>
					<!-- X, Y 좌표 List -->
					<Polygon>
						<Point2D>0,0</Point2D>
						<Point2D>10,0</Point2D>
						<Point2D>10,10</Point2D>
						<Point2D>0,10</Point2D>
					</Polygon>
				</Boundary>
				<LinkedZoneIDList>
					<!-- 최소 1개 이상 있어야 한다. -->
					<ZoneID>Z_1</ZoneID>
				</LinkedZoneIDList>
				<!-- 생략가능 -->
				<!-- Type의 의미는 프로젝트에 따라 각기 설정한다. -->
				<Type>0</Type>
				<!-- 생략가능 -->
				<TextCenter>
					<Point3D>0,0,0</Point3D>
				</TextCenter>
				<!-- 생략가능 -->
				<DisplayText>1-1공장 1층 사무실</DisplayText>
				<!-- 생략가능 -->
				<BroadcastText>일 다시 일 공장 일층 사무실</BroadcastText>
			</EquipmentZone>
		</EquipmentZones>
	</Spaces>
	<Sensors>
		<SensorTypes>
			<SensorType id="ST_0">
				<Name>화재</Name>
			</SensorType>
			<SensorType id="ST_11">
				<Name>누출</Name>
			</SensorType>
		</SensorTypes>
		<FireSensorSubTypes>
			<FireSensorSubType id="FST_-1">
				<Name>일반 감지기</Name>
			</FireSensorSubType>
			<FireSensorSubType id="FST_0">
				<Name>열 감지기</Name>
			</FireSensorSubType>
			<FireSensorSubType id="FST_1">
				<Name>연기 감지기</Name>
			</FireSensorSubType>
			<FireSensorSubType id="FST_2">
				<Name>불꽃 감지기</Name>
			</FireSensorSubType>
		</FireSensorSubTypes>
		<Materials>
			<Material id="M_1">
				<Name>암모니아</Name>
				<UOM>ppm</UOM>
			</Material>
		</Materials>
		<FireSensors>
			<Fire id="FS_1">
				<Name></Name>
				<!-- 생략가능 -->
				<PositionName></PositionName>
				<Position>
					<!-- Point3D가 정의되어 있지 않으면 아직 위치가 결정되지 않은 것이다. -->
					<Point3D>0,0,0</Point3D>
				</Position>
				<ZoneID>Z_1</ZoneID>
				<!-- 생략가능 -->
				<EquipZoneID>EZ_1</EquipZoneID>
				<!-- 생략가능 -->
				<SensorSubType>FST_2</SensorSubType>
			</Fire>
		</FireSensors>
		<PSMSensors>
			<PSM id="PS_1">
				<Name></Name>
				<!-- 생략가능 -->
				<PositionName></PositionName>
				<Position>
					<!-- Point3D가 정의되어 있지 않으면 아직 위치가 결정되지 않은 것이다. -->
					<Point3D>0,0,0</Point3D>
				</Position>
				<ZoneID>Z_1</ZoneID>
				<!-- 생략시 아직 데이터 설정이 끝나지 않은 것이다. -->
				<EquipZoneID>EZ_1</EquipZoneID>
				<MaterialID>M_1</MaterialID>
			</PSM>
		</PSMSensors>
		<EtcSensors>
			<Etc id="ES_1">
				<Name></Name>
				<!-- 생략가능 -->
				<PositionName></PositionName>
				<Position>
					<!-- Point3D가 정의되어 있지 않으면 아직 위치가 결정되지 않은 것이다. -->
					<Point3D>0,0,0</Point3D>
				</Position>
				<ZoneID>Z_1</ZoneID>
				<!-- 생략시 아직 데이터 설정이 끝나지 않은 것이다. -->
				<EquipZoneID>EZ_1</EquipZoneID>
			</Etc>
		</EtcSensors>
		<CCTVs>
			<CCTV id="CC_1">
				<Name></Name>
				<!-- 생략가능 -->
				<PositionName></PositionName>
				<Position>
					<!-- Point3D가 정의되어 있지 않으면 아직 위치가 결정되지 않은 것이다. -->
					<Point3D>0,0,0</Point3D>
				</Position>
				<ZoneID>Z_1</ZoneID>
				<!-- 생략시 아직 데이터 설정이 끝나지 않은 것이다. -->
				<EquipZoneID>EZ_1</EquipZoneID>
			</CCTV>
		</CCTVs>
	</Sensors>
	
</UnE.Space.Sensor>
